/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leaning;

import org.testng.annotations.*;
import static org.testng.Assert.*;

import static org.hamcrest.CoreMatchers.*;

import java.util.*;

import json.*;
import json.gson.GsonTester;

public class GsonTest {
    GsonTester tester;

    List<Student> toList;

    @BeforeClass
    public void init() {
        
        toList = new ArrayList<Student>(Arrays.asList(
            new Student("101", "학생1", 15, 2),
            new Student("102", "학생2", 16, 3),
            new Student("103", "학생3", 14, 1),
            new Student("104", "학생4", 15, 2),
            new Student("105", "학생5", 16, 2)
        ));
    }

    @BeforeTest
    public void setUp() {
        tester  = new GsonTester();
    }

    @Test 
    public void convertToObject() {
        Student student = new Student();
        student.setNo("101");
        student.setName("학생1");
        student.setAge(15);
        student.setGrade(3);

        Student convertStudent = tester.convertStringToObject("101", "학생1", 15, 3);

        isSameStudent(student, convertStudent);
    }

    @Test
    public void convertToList() {
        String jsonString = makeJsonString();

        List<Student> result = tester.convertStringToList(jsonString);

        assertEquals(toList.size(), result.size());
    }

    @Test
    public void convertObjectTostring() {
        String makeJsonString = "";
        String itsJsonString = "";
        for( Student student : toList ) {
            itsJsonString = "{\"no\":\""+ student.getNo() + "\",\"name\":\""+ student.getName() + "\",\"age\":"+ student.getAge() + ",\"grade\":"+ student.getGrade() + "}";
            makeJsonString = tester.convertObjectTostring(student);

            assertEquals(itsJsonString, makeJsonString);
        }
    }

    @Test
    public void parsingStringGetField() {
        Student student = toList.get(0);
        String thisFormat = String.format("no : %s, name : %s, age : %d, grade : %d", student.getNo(), student.getName(), student.getAge(), student.getGrade());

        String itsJsonString = "{\"no\":\""+ student.getNo() + "\",\"name\":\""+ student.getName() + "\",\"age\":"+ student.getAge() + ",\"grade\":"+ student.getGrade() + "}";

        String returnFormat = tester.parsingStringGetField(itsJsonString);

        assertEquals(thisFormat, returnFormat);
    }

    private String makeJsonString() {
        String jsonString = "[";

        for (Student student : toList) {
            jsonString = jsonString + "{\"no\":\""+ student.getNo() + "\",\"name\":\""+ student.getName() + "\",\"age\":"+ student.getAge() + ",\"grade\":"+ student.getGrade() + "},";
        }

        jsonString = jsonString.substring(0, jsonString.lastIndexOf(","));

        jsonString = jsonString + "]";
        return jsonString;
    }

    private void isSameStudent(Student source, Student target) {
        assertEquals(source, target);
        assertEquals(source.getNo(), target.getNo());
        assertEquals(source.getName(), target.getName());
        assertEquals(source.getAge(), target.getAge());
        assertEquals(source.getGrade(), target.getGrade());
    }

}
