/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leaning;

import org.testng.annotations.*;
import static org.testng.Assert.*;

import static org.hamcrest.CoreMatchers.*;

import json.*;
import json.gson.GsonTester;

public class GsonTest {
    @Test 
    public void convertToObject() {
        GsonTester tester  = new GsonTester();

        Student student = new Student();
        student.setNo("101");
        student.setName("학생1");
        student.setAge(15);
        student.setGrade(3);

        Student convertStudent = tester.convertStringToObject("101", "학생1", 15, 3);

        isSameStudent(student, convertStudent);
    }

    private void isSameStudent(Student source, Student target) {
        assertEquals(source, target);
        assertEquals(source.getNo(), target.getNo());
        assertEquals(source.getName(), target.getName());
        assertEquals(source.getAge(), target.getAge());
        assertEquals(source.getGrade(), target.getGrade());
    }

}
